# Generated by Django 3.1.7 on 2021-03-19 20:43

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('banner', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/amitdagar/Documents/work/projects/csivit/backend/media'), upload_to='products')),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
