# Generated by Django 3.1.7 on 2021-03-19 21:28

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20210319_2046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('delivery', models.IntegerField(default=2)),
                ('status', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/amitdagar/Documents/work/projects/csivit/backend/media'), upload_to='agreements')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
