# Generated by Django 3.1.7 on 2021-03-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agreements',
            table='agreements',
        ),
    ]
