# Generated by Django 3.1.7 on 2021-03-19 21:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_auto_20210319_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/amitdagar/Documents/work/projects/csivit/backend/media'), upload_to='agreements'),
        ),
    ]
